# Generated by Django 3.2.9 on 2021-12-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_comment_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
