# Generated by Django 3.2.9 on 2021-12-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_board_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
