# Generated by Django 3.2.9 on 2021-12-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211214_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authority',
            field=models.IntegerField(default=0),
        ),
    ]
